### ISSUE TITLE
_yaml UnYaml spec for UnCli

### ISSUE THREAD

**Issue by drernie** [data-yaml/udc#8]
- Create generic UnYaml parser
- Rewrite cli.yaml as an UnCli app

```yaml
_yaml:
  _version: 0.1.0
 app: UnCli
 app_version: 0.1.0
doc: udc
doc_version: 0.1.0
```
